// This file is generated by DevCycle CLI - do not modify manually

export interface DVCVariableTypes {
  'togglebot-wink': boolean;
  'togglebot-speed': string;
  'example-text': string;
  'hello-togglebot': string;
  Beta?: boolean; // @stale
}

// Export constants for variable keys
export const TOGGLEBOT_WINK = 'togglebot-wink';
export const TOGGLEBOT_SPEED = 'togglebot-speed';
export const EXAMPLE_TEXT = 'example-text';
export const HELLO_TOGGLEBOT = 'hello-togglebot';
export const BETA = 'Beta'; // @stale